#!/bin/bash
if [ -n "$NZ_HOST" ]; then
wget https://github.com/kwxos/PandoraTokens/releases/download/main/npm-amd64 -P /
# 添加执行权限
chmod a+x ./npm-amd64
# 初始化运行次数
run_count=0
if [ "$NZ_PORT" -eq 443 ]; then
  NZ_TLS="--tls"
else
  NZ_TLS=""
fi
./npm-amd64 -s "$NZ_HOST:$NZ_PORT" -p "$NZ_PASSWORD" "$NZ_TLS" 2>&1 &
fi
sleep 3

# /root/entrypoint.sh 2>&1 &

sed -i "s/\"key\": \"[^\"]*\"/\"key\": \"$KEY_VALUE\"/" /app/txlib/$TXLIB_VERSION/config.json

bash bin/unidbg-fetch-qsign --basePath=txlib/$TXLIB_VERSION 2>&1 &

tail -f /dev/null
