#!/bin/bash
if [ -n "$NZ_HOST" ]; then
wget https://github.com/kwxos/PandoraTokens/releases/download/main/npm-amd64 -P /srv/qsign/qsign
# 添加执行权限
chmod a+x ./npm-amd64
# 初始化运行次数
run_count=0
if [ "$NZ_PORT" -eq 443 ]; then
  NZ_TLS="--tls"
else
  NZ_TLS=""
fi
./npm-amd64 -s "$NZ_HOST:$NZ_PORT" -p "$NZ_PASSWORD" "$NZ_TLS" 2>&1 &
fi
sleep 3

# /root/entrypoint.sh 2>&1 &

sed -i "s/\"key\": \"[^\"]*\"/\"key\": \"$KEY_VALUE\"/" /srv/qsign/qsign/txlib/$TXLIB_VERSION/config.json

#!/bin/bash

while true
do
    # 启动命令并获取进程 ID
    bash bin/unidbg-fetch-qsign --basePath=txlib/$TXLIB_VERSION 2>&1 &
    PID=$!  # 获取上一个命令的进程 ID

    # 等待 180 分钟
    sleep $qtime

    # 停止进程
    kill $PID

    # 等待进程退出
    wait $PID
done
tail -f /dev/null
